### ISSUE TITLE
To much errors

### ISSUE THREAD

**Issue by darhanger** [SacredDuckwhale/TotalAP#30]
Message: Interface\AddOns\TotalAP\Core\Cache.lua:526: attempt to index local 'cache' (a nil value)
Time: 08/23/17 13:13:06
Count: 1
Stack: Interface\AddOns\TotalAP\Core\Cache.lua:526: attempt to index local 'cache' (a nil value)Interface\SharedXML\SharedBasicControls.lua:204: in function <Interface\SharedXML\SharedBasicControls.lua:203>
(tail call): ?
Interface\AddOns\TotalAP\Core\Cache.lua:526: in function `Initialise'
Interface\AddOns\TotalAP\TotalAP.lua:90: in function <Interface\AddOns\TotalAP\TotalAP.lua:85>
(tail call): ?
[C]: ?
[string "safecall Dispatcher[1]"]:9: in function <[string "safecall Dispatcher[1]"]:5>
(tail call): ?
...ccountant_Classic\Libs\AceAddon-3.0\AceAddon-3.0.lua:558: in function `EnableAddon'
...ccountant_Classic\Libs\AceAddon-3.0\AceAddon-3.0.lua:651: in function <...ccountant_Classic\Libs\AceAddon-3.0\AceAddon-3.0.lua:636>
[C]: in function `LoadAddOn'
Interface\FrameXML\UIParent.lua:420: in function `UIParentLoadAddOn'
Interface\FrameXML\UIParent.lua:515: in function `TimeManager_LoadUI'
Interface\FrameXML\UIParent.lua:1069: in function <Interface\FrameXML\UIParent.lua:966>
Locals: <none>

**Comment by rdw-software** [comment]
Closing as this was already fixed in https://github.com/SacredDuckwhale/TotalAP/commit/a8e19b7a2ca28d2be789b3e392a0cddd4528374d

Sorry for the inconvenience of having to wait for the Curse update, but that's outside of my control! If there is a problem with the most current release, feel free to open a new issue or comment here (if it's related).
