### ISSUE TITLE
Feature Request: Auto Sell

### ISSUE THREAD

**Issue by puggan** [SacredDuckwhale/TotalAP#32]
When you maxed the AP on your weapons, you still get items that are of no use.
Some way to easy sell the AP-items, preferly a setting to automatic sell them, but just modifing the box showing the items, so it sell them if current weapon is max, and a vendor is open, is useful to.

**Comment by rdw-software** [comment]
I'm not sure this fits too well with the addon, as there are excellent junk-selling addons out there and I see little reason to duplicate their functionality.

What could probably work would be adding an interface for un/marking AP tokens as "junk" when using the most popular ones (Scrap, JunkSeller, ..., ?) and then leaving it up to them to sell the tokens.

I'm not sure what you mean with "modifying the box", do you mean the action button showing them or just the item in your inventory? Also, I assume you'd want to sell them only if all specs are maxed, or also if the main spec is maxed (as some people don't use their offspecs at all)?

Edit: I was also under the impression that tier 2 artifacts are virtually impossible to max due to exponentially increasing costs. That would be another point of confusion.

**Comment by puggan** [comment]
"excellent junk-selling addons"
Yes, I'm so used to them, so now when my bags fill up with those ap-tokens, that i think is junk, I have to manually clean my bag.

As your addon already identifies them, and show them in a "box":
![totalapbutton](https://user-images.githubusercontent.com/866668/29750802-b4b9bc42-8b46-11e7-97b4-d158e9c46dc9.jpeg)

some way to sell them would be nice, from that box is one way, then i don't have to go through my bags, as the addon works now, it's just hide that box when the equiped weapon is maxed out.

Mark them as junk for other addons would be nice too.

"tier 2 artifacts"
Have no clue about them, as I don't have time to play much, haven't raided since level 80.

**Comment by rdw-software** [comment]
Okay, I will look into this (when I get around to it) and see if I can interface Scrap, JunkSeller and any other similar addon that I can find. The "box" is an ActionButton and can't be used to sell items (I think), but having an option to automatically mark items as junk would be quite useful, even for regular users who just want to get rid of the low-value tokens (as they still vendor for a bit).

The point is, if you do the empowerment quest in Dalaran (or wait until 7.3 hits, when it will unlock automatically), your artifact won't be maxed anymore :) The feature could still be useful, so I'm keeping the idea alive.

Possible roadmap:
- [ ] Add interface to popular junk selling addons, to allow marking AP items as "junk" (and unmarking them) dynamically
- [ ] Add option to enable/disable the tagging for maxed artifacts
- [ ] Optional: Add setting to allow "filtering" (and tagging) for AP items below a certain threshold (probably requires #15)

**Comment by rdw-software** [comment]
I'm closing this, as 7.3 removed the vendor price and also automatically unlocks artifact tier 2, which is virtually impossible to max anyway. Therefore, this feature will no longer be useful to anybody at all... if it ever was :)
