### ISSUE TITLE
Error with thousand separator in ruRu client

### ISSUE THREAD

**Issue by darhanger** [SacredDuckwhale/TotalAP#38]
Message: Interface\AddOns\TotalAP\Core\Scanner.lua:66: attempt to index local 'm' (a nil value)
Time: 09/06/17 22:46:01
Count: 5
Stack: Interface\AddOns\TotalAP\Core\Scanner.lua:66: attempt to index local 'm' (a nil value)
(tail call): ?
Interface\AddOns\TotalAP\Core\Scanner.lua:66: in function `ParseSpellDesc'
...ce\AddOns\TotalAP\Core\Controllers\EventHandlers.lua:108: in function <...ce\AddOns\TotalAP\Core\Controllers\EventHandlers.lua:34>
...ce\AddOns\TotalAP\Core\Controllers\EventHandlers.lua:156: in function <...ce\AddOns\TotalAP\Core\Controllers\EventHandlers.lua:154>
...ce\AddOns\TotalAP\Core\Controllers\EventHandlers.lua:246: in function <...ce\AddOns\TotalAP\Core\Controllers\EventHandlers.lua:241>
[string "safecall Dispatcher[1]"]:4: in function <[string "safecall Dispatcher[1]"]:4>
[C]: ?
[string "safecall Dispatcher[1]"]:13: in function `?'
...sic\Libs\CallbackHandler-1.0\CallbackHandler-1.0.lua:90: in function `Fire'
...ccountant_Classic\Libs\AceEvent-3.0\AceEvent-3.0.lua:120: in function <...ccountant_Classic\Libs\AceEvent-3.0\AceEvent-3.0.lua:119>

Locals: <none>

https://github.com/SacredDuckwhale/TotalAP/blob/152bb17f04f7dd81e86d9a080f8b19bc8d93469b/Core/Scanner.lua#L66

Completely broken, and I do not know what it's all about. I think that it is necessary to do the same as in Pawn, a separate localization file and digital separators.

**Comment by rdw-software** [comment]
I've taken a look at Pawn; they don't seem to be using custom separators though. TotalAP's number formats are localised in [Locales\NumberFormats.lua](https://github.com/SacredDuckwhale/TotalAP/blob/master/Locales/NumberFormats.lua) - unfortunately the ruRU and zhCN entries are somewhat experimental (as I can't use a max level character to test them).

If the formats are still wrong, you should be able to fix them by editing this file with the correct separators and/or units. I've tested them with a level 1 character and had no errors pop up but I can't do more at this point. I'll gladly add any corrections you might have :)

(You can navigate to the "ruRU" entry and see if something is off)

**Comment by darhanger** [comment]
A special for you, make video

https://www.youtube.com/watch?v=fHbrAPFqP9g

When in the bag AP items with  separator (like on video 46,4) pop up window with error. they are also not displayed in addon UI. Once used, and leave in a bag items with integer numbers. The error does not occur

**Comment by rdw-software** [comment]
The video is unavailable/private :)

As far as I understand it, the thousands separator is causing issues. Could you post a screenshot (upload to [imgur](http://imgur.com) or something of the item causing issues vs one of an item not causing any problems? I'd need to see the spell description ("Use to apply X Artifact Power to your weapon"), which is being scanned.

I tested all items in the DB at current Artifact Knowledge levels using the ruRU client (but on a level 1 character) without encountering an error. Not sure what is going wrong here, but it needs to be fixed obviously.

-------------------------

**EDIT: Nevermind the above.**

I went through quite some effort to narrow this down, and after comparing all possible combinations of formats and even writing dedicated tests to cover the Scanner for all locales, I believe the fix was simply the wrong decimal separator ("." instead of ","). Please try the next release and let me know if this was it.

I'll leave the issue open until I have confirmation that this works. It SHOULD be fixed by a015c45f6ce46203c6220cf0bebdcc4d2a3c4af1, though.

**Comment by darhanger** [comment]
All fine. All work correct. Now i'm testing.

**Comment by rdw-software** [comment]
Closing this as fixed. Feel free to comment if the same problem occurs, or open a new issue if an unrelated error manifests.
